language: android

sudo: false

android:
  components:
  - tools
  - build-tools-27.0.3
  - android-26
  - extra-android-m2repository
  - extra-android-support
  
before_install:     
 - chmod +x gradlew
 
script:
  - ./gradlew clean
  - ./gradlew assembleRelease
